[project]
name = "zoomin-zoomout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cvzone>=1.6.1",
    "mediapipe>=0.10.21",
]
